### ISSUE TITLE
Design Manage

### ISSUE THREAD

**Issue by SilviaZeta** [gliff-ai/manage#68]
**Is your feature request related to a problem? Please describe.**
We need a design for manage.

At the moment we have:
- A "projects" page
- A "users" page

Features for "projects" page:
- Create new project
- List all existing projects
- Invite a new user to a project

What "projects" looks like:

<img width="445" alt="Screenshot 2021-06-23 at 15 23 47" src="https://user-images.githubusercontent.com/13273585/123114169-08271180-d437-11eb-9bca-84489dff47c6.png">

Features for "users" page:
- List all users
- List pending invites (email and sent date)
- Select a user email and send an invite

What "users" looks like:

<img width="378" alt="Screenshot 2021-06-23 at 15 23 37" src="https://user-images.githubusercontent.com/13273585/123114182-0cebc580-d437-11eb-9241-f1915b7b3b92.png">

**Describe the solution you'd like**
?

**Describe alternatives you've considered**
N/A

**Additional context**
No

**Comment by joshuajames-smith** [comment]
As there is not as much content or functions as annotate or curate at the moment, I have played on the side of designing sparsely with space in which future ideas and content will want to find their home. 

manage UI layout is very similar to curate. The left-hand short toolbar allows the user to switch between the 'users' and 'projects' pages. They should be styled and be interacted with like any other icon, it should have tooltips to ensure users know what the icons do. So far, I thought just the project title and team members would good to show at this stage.
![Interface Layout -  projects](https://user-images.githubusercontent.com/83074763/123460072-fed8a900-d5de-11eb-8b96-cf0550df943c.png)

By clicking on the top option, the user can create a new project. In a similar manner to say how curate about how a new collection is created [https://github.com/gliff-ai/curate/issues/68]. An opaque grey box should push the design into the background to allow the pop-up to stand out. At the moment, they can give the project a name and then from a dropdown menu access which team member they want.
![Interface Layout -  projects  -  create a new project  - stage 1](https://user-images.githubusercontent.com/83074763/123460725-faf95680-d5df-11eb-9d5a-2aa8178faab0.png)

Used a blue hover state instead of green to try and bring some more of the gliff colours back into the design. This helps users know which option they are on, a single-click and that team member is assigned to this project.
![Interface Layout -  projects  -  create a new project  - stage 2](https://user-images.githubusercontent.com/83074763/123460783-12d0da80-d5e0-11eb-886c-f2ff46cad098.png)

Once clicked, the option should disappear and the dropdown menu is resized accordingly.
![Interface Layout -  projects  -  create a new project  - stage 3](https://user-images.githubusercontent.com/83074763/123460885-385de400-d5e0-11eb-95bc-bffcfbaeed4e.png)

The user then has a list of team members, in a similar way they just single-click and can remove a team member from the project. The other buttons allow them to cancel the action or to confirm.
![Interface Layout -  projects  -  create a new project  - stage 4](https://user-images.githubusercontent.com/83074763/123460930-4ca1e100-d5e0-11eb-85d5-a9ccf83404b9.png)

Finally, the new project is added to the list. For now this work, but after many projects, a search feature may need to be built-in. Similarly, other data in the future may be added (like progress, or team member pictures) may help enhance and offer the users a better overview of their projects.
![Interface Layout -  projects  -  create a new project  - stage 5](https://user-images.githubusercontent.com/83074763/123461074-81159d00-d5e0-11eb-90cc-bd2eeade8908.png)

Similiary, I kept the 'users' page simple too. A list of users is displayed in the active user's panel, both name and email. This should update every time an invite is accepted. The invites panel allows the user to see pending invites, in this case the user has none and that is shown by centred text in the space. Also a text box to allow them to input an email and send an invite.
![Interface Layout -  users  -  no pending invites](https://user-images.githubusercontent.com/83074763/123461226-c043ee00-d5e0-11eb-8e03-623e21e76648.png)

If the user sends invites, their pending invites are displayed in grey showing their email and date of invitation. Assuming once they have accepted they move from the pending to active user list.
![Interface Layout -  users  -  2 pending invites](https://user-images.githubusercontent.com/83074763/123461470-11ec7880-d5e1-11eb-8ccd-b55bc0892b9d.png)



[all icons are located in the Google Drive > UI/UX folder for 'manage']
https://xd.adobe.com/view/ff9afeff-e9a8-48b7-85d7-f387fcbcb37b-aac9/
